services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo18-custom
    container_name: odoo18
    depends_on:
      - db
    # Pass DB and logging parameters explicitly so env vars are honored
    # and logs are emitted to stdout (visible via `docker compose logs`).
    command: >-
      --db_host=${ODOO_DB_HOST}
      --db_port=${ODOO_DB_PORT}
      --db_user=${ODOO_DB_USER}
      --db_password=${ODOO_DB_PASSWORD}
      -d ${ODOO_DB_NAME}
      --logfile=-
    environment:
      DB_HOST: ${ODOO_DB_HOST}
      DB_PORT: ${ODOO_DB_PORT}
      DB_USER: ${ODOO_DB_USER}
      DB_PASSWORD: ${ODOO_DB_PASSWORD}
      DB_NAME: ${ODOO_DB_NAME}
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./oca:/mnt/oca
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
