services:
  db:
    image: postgres:15
    container_name: odoo-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    image: odoo18-custom
    container_name: odoo18
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: ${ODOO_DB_HOST}
      DB_PORT: ${ODOO_DB_PORT}
      DB_USER: ${ODOO_DB_USER}
      DB_PASSWORD: ${ODOO_DB_PASSWORD}
      DB_NAME: ${ODOO_DB_NAME}
      ADMIN_PASSWORD: ${ODOO_ADMIN_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./oca:/mnt/oca
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
